name: bikeshare_streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - pip
  - numpy
  - pandas
  - matplotlib
  - streamlit
  - geopy
  - geopandas
  - folium
  - pip:
    - streamlit-folium==0.22.1
    - pyautogui
    - watchdog
